apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proof-of-concept-nginx
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: proof-of-concept
  project: proof-of-concept
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.8.0
    helm:
      parameters:
      - name: 'service.type'
        value: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
