apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: proof-of-concept
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo CD
  sourceRepos:
  - 'https://charts.bitnami.com/bitnami'
  destinations:
  - namespace: proof-of-concept
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
