apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argo-cd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo CD Default Project - DO NOT USE
  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  - namespace: proof-of-concept
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'    
  orphanedResources:
    warn: true
    ignore:
    - group: "*"
      kind: "Secret"
      name: "istio.*"