---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: apps/
    repoURL: https://github.com/suhasgaddam-trueaccord/argo-cd.git
    targetRevision: qa01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
