apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd
  namespace: argo-cd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo CD

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
