apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd
  namespace: argo-cd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  description: Argo CD
  sourceRepos:
  - 'https://github.com/suhasgaddam-trueaccord/argo-cd.git'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://dandydeveloper.github.io/charts'
  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  orphanedResources:
    warn: true
    ignore:
    - group: "*"
      kind: "Secret"
      name: "istio.*"
